// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using proekt.Database;

#nullable disable

namespace proekt.Migrations
{
    [DbContext(typeof(StudSessionDbContext))]
    partial class StudSessionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("proekt.Models.StudSession", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grade_id")
                        .HasComment("Идентификатор успеваемости");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradeId"));

                    b.Property<DateTime?>("GradeDate")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("c_student_gradedate")
                        .HasComment("Дата оценки");

                    b.Property<int?>("GradeNumber")
                        .IsRequired()
                        .HasColumnType("int4")
                        .HasColumnName("c_student_gradenumber")
                        .HasComment("Оценка");

                    b.Property<int?>("StudentId")
                        .IsRequired()
                        .HasColumnType("int4")
                        .HasColumnName("c_student_studentid")
                        .HasComment("Идентификатор студента");

                    b.HasKey("GradeId")
                        .HasName("pk_(TableName)_GradeId");

                    b.HasIndex(new[] { "StudentId" }, "idx_(TableName)_fk_f_student_id");

                    b.ToTable("StudSession", (string)null);
                });

            modelBuilder.Entity("proekt.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("student_id")
                        .HasComment("Идентификатор записи студента");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_student_firstname")
                        .HasComment("Имя студента");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_student_lastname")
                        .HasComment("Фамилия студента");

                    b.Property<string>("SecName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_student_secname")
                        .HasComment("Отчество студента");

                    b.HasKey("StudentId")
                        .HasName("pk_(TableName)_StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("proekt.Models.StudSession", b =>
                {
                    b.HasOne("proekt.Models.Student", "Student")
                        .WithMany("StudSession")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_student_id");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("proekt.Models.Student", b =>
                {
                    b.Navigation("StudSession");
                });
#pragma warning restore 612, 618
        }
    }
}
